<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here

	'Class:IPInterface/Attribute:mtu' => 'MTU',
	'Class:IPInterface/Attribute:mtu+' => 'Maximum Transmission Unit',
	'Class:IPInterface/Attribute:speed' => 'Interface Speed',
	'Class:IPInterface/Attribute:speed+' => 'Physical Interface information rate',

	'Class:PhysicalInterface/Attribute:media_type' => 'Media Type',
	'Class:PhysicalInterface/Attribute:media_type+' => 'Media Type of the interface',
	'Class:PhysicalInterface/Attribute:port_type' => 'Port Type',
	'Class:PhysicalInterface/Attribute:port_type+' => 'Port Type of the interface',
	'Class:PhysicalInterface/Attribute:circuit_list' => 'Circuits',
	'Class:PhysicalInterface/Attribute:circuit_list+' => 'Physical Interface is linked with the following Circuits',

	'Class:FunctionalCI/Attribute:move2production' => 'Production Start',
	'Class:FunctionalCI/Attribute:move2production+' => 'Date when production started and the service becomes chargable',
	'Class:FunctionalCI/Attribute:business_criticity' => 'Criticality',
	'Class:FunctionalCI/Attribute:business_criticity/Value:high' => 'high',
	'Class:FunctionalCI/Attribute:business_criticity/Value:high+' => 'high',
	'Class:FunctionalCI/Attribute:business_criticity/Value:low' => 'average',
	'Class:FunctionalCI/Attribute:business_criticity/Value:low+' => 'average',
	'Class:FunctionalCI/Attribute:business_criticity/Value:medium' => 'normal',
	'Class:FunctionalCI/Attribute:business_criticity/Value:medium+' => 'normal',

	'Class:Problem/Attribute:impact/Value:1' => 'Entire Services',
	'Class:Problem/Attribute:impact/Value:1+' => 'e.g. all circuits or entire application',
	'Class:Problem/Attribute:impact/Value:2' => 'Multiple Service Locations',
	'Class:Problem/Attribute:impact/Value:2+' => 'e.g. several circuits or multiple users',
	'Class:Problem/Attribute:impact/Value:3' => 'Single Service Location',
	'Class:Problem/Attribute:impact/Value:3+' => 'e.g. one circuit or one user',

	'Class:Change/Attribute:impact/Value:1' => 'Entire Services',
	'Class:Change/Attribute:impact/Value:1+' => 'e.g. all circuits or entire application',
	'Class:Change/Attribute:impact/Value:2' => 'Multiple Service Locations',
	'Class:Change/Attribute:impact/Value:2+' => 'e.g. several circuits or multiple users',
	'Class:Change/Attribute:impact/Value:3' => 'Single Service Location',
	'Class:Change/Attribute:impact/Value:3+' => 'e.g. one circuit or one user',

	'Class:Room/Attribute:access' => 'Access restrictions',
	'Class:Room/Attribute:access+' => 'Access restrictions governed by organization in charge',
	'Class:Room/Attribute:organizationincharge' => 'In charge',
	'Class:Room/Attribute:organizationincharge+' => 'Organization in charge',
	'Class:Room/Attribute:access/Value:1' => 'no restrictions',
	'Class:Room/Attribute:access/Value:1+' => 'access and work without any restrictions',
	'Class:Room/Attribute:access/Value:2' => 'partially restricted',
	'Class:Room/Attribute:access/Value:2+' => 'access and work paritally restricted',
	'Class:Room/Attribute:access/Value:3' => 'PMB - Access Level 1',
	'Class:Room/Attribute:access/Value:3+' => 'Prasarana work permit required (unpaid area, outside station)',
	'Class:Room/Attribute:access/Value:4' => 'PMB - Access Level 2',
	'Class:Room/Attribute:access/Value:4+' => 'Prasarana work permit and supervisor required (room in unpaid area)',
	'Class:Room/Attribute:access/Value:5' => 'PMB - Access Level 3',
	'Class:Room/Attribute:access/Value:5+' => 'Prasarana work permit and supervisor required (platform, concourse, rooftop, paid area)',
	'Class:Room/Attribute:access/Value:6' => 'PMB - Access Level 4',
	'Class:Room/Attribute:access/Value:6+' => 'Prasarana work permit, OC clearance and supervisor required (track, tunnel, envelope, power rail vicinity)',
	'Class:Room/Attribute:areaimage' => 'Image',
	'Class:Room/Attribute:areaimage+' => 'Image will be reduced to 500px x 375px',
	
));

//
// Class: Cabinet
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:Cabinet' => 'Cabinet',
	'Class:Cabinet+' => '',
	'Class:Cabinet/Attribute:cabinetfunction' => 'Cabinet Function',
	'Class:Cabinet/Attribute:cabinetfunction+' => 'For what the cabinet is used',
	'Class:Cabinet/Attribute:cabinetfunction/Value:1' => 'FDC',
	'Class:Cabinet/Attribute:cabinetfunction/Value:1+' => 'FDC',
	'Class:Cabinet/Attribute:cabinetfunction/Value:2' => 'NodeB',
	'Class:Cabinet/Attribute:cabinetfunction/Value:2+' => 'NodeB',
	'Class:Cabinet/Attribute:cabinetfunction/Value:3' => 'AC Power',
	'Class:Cabinet/Attribute:cabinetfunction/Value:3+' => 'AC Power',
	'Class:Cabinet/Attribute:cabinetfunction/Value:4' => 'AC MDB',
	'Class:Cabinet/Attribute:cabinetfunction/Value:4+' => 'AC MDB',
	'Class:Cabinet/Attribute:cabinetfunction/Value:5' => 'General Equipment',
	'Class:Cabinet/Attribute:cabinetfunction/Value:5+' => 'General Equipment',
	'Class:Cabinet/Attribute:cabinetfunction/Value:6' => 'Other',
	'Class:Cabinet/Attribute:cabinetfunction/Value:6+' => 'Other',
));

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here
	// Circuit related entries
	
	'Class:CircuitType/Attribute:name' => 'Name',
	'Class:CircuitType/Attribute:name+' => 'Name',
    'Class:CircuitType/Attribute:description' => 'Description',
	'Class:CircuitType/Attribute:description+' => 'Description',
	'Class:Circuit:baseinfo' => 'General Information',
	'Class:Circuit:downlink_primary' => 'Primary Down-Link',
	'Class:Circuit:uplink_primary' => 'Primary Up-Link (POI)',
	'Class:Circuit/Attribute:physicalinterfaces_list' => 'Network Interfaces',
	'Class:Circuit/Attribute:physicalinterfaces_list+' => 'Circuit is associated with the following interfaces',
	'Class:Circuit/Attribute:type_name' => 'typeName',
	'Class:Circuit/Attribute:type_name+' => 'typeName with more explanations',
	
	'Class:Circuit/Attribute:status' => 'Circuit Status',
	'Class:Circuit/Attribute:status+' => 'Status of the circuit',
	'Class:Circuit/Attribute:customer_id' => 'Customer',
	'Class:Circuit/Attribute:customer_id+' => 'Customer - Party which signed the contract',
	'Class:Circuit/Attribute:customer_name' => 'Customer Name',
	'Class:Circuit/Attribute:customer_name+' => 'Customer - Party who signed the contract',
	'Class:Circuit/Attribute:customer_reference' => 'Customer Reference',
	'Class:Circuit/Attribute:customer_reference+' => 'Circuit reference given by the customer',

	'Class:Circuit/Attribute:purchase_date' => 'Purchased',
	'Class:Circuit/Attribute:purchase_date+' => 'The date the customer placed the order (e.g. signed LOO - Letter of Offer)',
	'Class:Circuit/Attribute:uat_date' => 'UAT',
	'Class:Circuit/Attribute:uat_date+' => 'The date on which the User Acceptance Test has been signed',
	'Class:Circuit/Attribute:renewal_date' => 'Renewal',
	'Class:Circuit/Attribute:renewal_date+' => 'Date of renewal for non-perpetual contracts',
	'Class:Circuit/Attribute:decommissioning_date' => 'Decom',
	'Class:Circuit/Attribute:decommissioning_date+' => 'Decommissioning date',

	'Class:Circuit:configuration' => 'Configuration Information',
	'Class:Circuit/Attribute:type_id' => 'Circuit Type',
    'Class:Circuit/Attribute:type_id+' => 'Circuit Type',
	'Class:Circuit/Attribute:l2protection' => 'L2 Protection',
	'Class:Circuit/Attribute:l2protection+' => 'L2 protection method',
	'Class:Circuit/Attribute:CIR' => 'CIR',
    'Class:Circuit/Attribute:CIR+' => 'Committed Information Rate',
	'Class:Circuit/Attribute:EIR' => 'EIR',
	'Class:Circuit/Attribute:EIR+' => 'Excess Information Rate',
	'Class:Circuit/Attribute:CBS' => 'CBS',
	'Class:Circuit/Attribute:CBS+' => 'Committed Burst Size',
	'Class:Circuit/Attribute:EBS' => 'EBS',
	'Class:Circuit/Attribute:EBS+' => 'Excess Burst Size',

	'Class:lnkPhysicalInterfaceToCircuit' => 'Link Physical Interface to Circuit',
	'Class:lnkPhysicalInterfaceToCircuit+' => 'Link Physical Interface to Circuit',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:port_sequence' => 'Port Sequence',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:port_sequence+' => 'P00 to P99 for primary link, S00 to S99 for secondary link.',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:circuit_id' => 'Circuit Name',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:circuit_id+' => 'Circuit Name',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:physicalinterface_id' => 'Physical Interface',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:physicalinterface_id+' => 'Name of the physical interface',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:speed' => 'Interface Speed',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:speed+' => 'Physical Interface information rate',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:port_function' => 'Interface Function',
	'Class:lnkPhysicalInterfaceToCircuit/Attribute:port_function+' => 'The function the interface has in context of the circuit',
));

// Class: PowerConnection
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:PowerConnection' => 'Power Connection',
	'Class:PowerConnection+' => '',
	'Class:PowerConnection/Attribute:voltage' => 'Rated Voltage (V)',
	'Class:PowerConnection/Attribute:voltage+' => '',
	'Class:PowerConnection/Attribute:voltage/Value:1' => '5',
	'Class:PowerConnection/Attribute:voltage/Value:1+' => '5',
	'Class:PowerConnection/Attribute:voltage/Value:2' => '12',
	'Class:PowerConnection/Attribute:voltage/Value:2+' => '12',
	'Class:PowerConnection/Attribute:voltage/Value:3' => '24',
	'Class:PowerConnection/Attribute:voltage/Value:3+' => '24',
	'Class:PowerConnection/Attribute:voltage/Value:4' => '48',
	'Class:PowerConnection/Attribute:voltage/Value:4+' => '48',
	'Class:PowerConnection/Attribute:voltage/Value:5' => '240',
	'Class:PowerConnection/Attribute:voltage/Value:5+' => '240',
	'Class:PowerConnection/Attribute:voltage/Value:6' => '400',
	'Class:PowerConnection/Attribute:voltage/Value:6+' => '400',
	'Class:PowerConnection/Attribute:current' => 'Rated Current (A)',
	'Class:PowerConnection/Attribute:current+' => '',
	'Class:PowerConnection/Attribute:current/Value:1' => '6',
	'Class:PowerConnection/Attribute:current/Value:1+' => '6',
	'Class:PowerConnection/Attribute:current/Value:2' => '16',
	'Class:PowerConnection/Attribute:current/Value:2+' => '16',
	'Class:PowerConnection/Attribute:current/Value:3' => '20',
	'Class:PowerConnection/Attribute:current/Value:3+' => '20',
	'Class:PowerConnection/Attribute:current/Value:4' => '25',
	'Class:PowerConnection/Attribute:current/Value:4+' => '25',
	'Class:PowerConnection/Attribute:current/Value:5' => '40',
	'Class:PowerConnection/Attribute:current/Value:5+' => '40',
	'Class:PowerConnection/Attribute:current/Value:6' => '63',
	'Class:PowerConnection/Attribute:current/Value:6+' => '63',
	'Class:PowerConnection/Attribute:current/Value:7' => '80',
	'Class:PowerConnection/Attribute:current/Value:7+' => '80',
	'Class:PowerConnection/Attribute:current/Value:8' => '100',
	'Class:PowerConnection/Attribute:current/Value:8+' => '100',
	'Class:PowerConnection/Attribute:current/Value:9' => '125',
	'Class:PowerConnection/Attribute:current/Value:9+' => '125',
	'Class:PowerConnection/Attribute:phases' => 'Power Phases',
	'Class:PowerConnection/Attribute:phases+' => '',
	'Class:PowerConnection/Attribute:phases/Value:1-Phase' => '1-Phase',
	'Class:PowerConnection/Attribute:phases/Value:1-Phase+' => '1-Phase',
	'Class:PowerConnection/Attribute:phases/Value:3-Phase' => '3-Phase',
	'Class:PowerConnection/Attribute:phases/Value:3-Phase+' => '3-Phase',
	'Class:PowerConnection/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:PowerConnection/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: PowerSource
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:PowerSource' => 'Power Source',
	'Class:PowerSource+' => '',
	'Class:PowerSource/Attribute:ACDB_A_list' => 'AC-DBs Power A',
	'Class:PowerSource/Attribute:ACDB_A_list+' => '',
	'Class:PowerSource/Attribute:ACDB_B_list' => 'AC-DBs Power B',
	'Class:PowerSource/Attribute:ACDB_B_list+' => '',
	'Class:PowerSource/Attribute:powerprovider_id' => 'Power Provider',
	'Class:PowerSource/Attribute:powerprovider_id+' => '',
	'Class:PowerSource/Attribute:PowerSubstation' => 'Power Substation',
	'Class:PowerSource/Attribute:PowerSubstation+' => '',
	'Class:PowerSource/Attribute:PowerMeter_id' => 'Power Meter',
	'Class:PowerSource/Attribute:PowerMeter_id+' => '',
	'Class:PowerSource/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:PowerSource/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:PowerSource/Attribute:powerprovider_id_friendlyname' => 'Power Provider Name',
	'Class:PowerSource/Attribute:powerprovider_id_friendlyname+' => 'Full name',
	'Class:PowerSource/Attribute:powerprovider_id_obsolescence_flag' => 'Obsolete',
	'Class:PowerSource/Attribute:powerprovider_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:PowerSource/Attribute:PowerMeter_id_friendlyname' => 'Power Meter Name',
	'Class:PowerSource/Attribute:PowerMeter_id_friendlyname+' => 'Full name',
	'Class:PowerSource/Attribute:PowerMeter_id_obsolescence_flag' => 'Obsolete',
	'Class:PowerSource/Attribute:PowerMeter_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: PDU
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:PDU' => 'Power PDU',
	'Class:PDU+' => '',
	'Class:PDU/Attribute:rack_id' => 'Rack',
	'Class:PDU/Attribute:rack_id+' => '',
	'Class:PDU/Attribute:rack_name' => 'Rack name',
	'Class:PDU/Attribute:rack_name+' => '',
	'Class:PDU/Attribute:powerstart_id' => 'Power start',
	'Class:PDU/Attribute:powerstart_id+' => '',
	'Class:PDU/Attribute:powerstart_name' => 'Power start name',
	'Class:PDU/Attribute:powerstart_name+' => '',
	'Class:PDU/Attribute:device_powerA_list' => 'Devices Power A',
	'Class:PDU/Attribute:device_powerA_list+' => '',
	'Class:PDU/Attribute:device_powerB_list' => 'Devices Power B',
	'Class:PDU/Attribute:device_powerB_list+' => '',
	'Class:PDU/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:PDU/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:PDU/Attribute:rack_id_friendlyname' => 'Rack',
	'Class:PDU/Attribute:rack_id_friendlyname+' => 'Full name',
	'Class:PDU/Attribute:rack_id_finalclass_recall' => 'CI sub-class',
	'Class:PDU/Attribute:rack_id_finalclass_recall+' => 'Name of the final class',
	'Class:PDU/Attribute:rack_id_obsolescence_flag' => 'Obsolete',
	'Class:PDU/Attribute:rack_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:PDU/Attribute:powerstart_id_friendlyname' => 'Power start',
	'Class:PDU/Attribute:powerstart_id_friendlyname+' => 'Full name',
	'Class:PDU/Attribute:powerstart_id_finalclass_recall' => 'CI sub-class',
	'Class:PDU/Attribute:powerstart_id_finalclass_recall+' => 'Name of the final class',
	'Class:PDU/Attribute:powerstart_id_obsolescence_flag' => 'Obsolete',
	'Class:PDU/Attribute:powerstart_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: PowerMeter
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:PowerMeter' => 'Power Meter',
	'Class:PowerMeter+' => '',
	'Class:PowerMeter/Attribute:rack_id' => 'Cabinet',
	'Class:PowerMeter/Attribute:rack_id+' => '',
	'Class:PowerMeter/Attribute:providermeterreference' => 'Provier Meter Reference',
	'Class:PowerMeter/Attribute:providermeterreference+' => 'Provier Meter Reference or ID',
	'Class:PowerMeter/Attribute:powerreadingfrequency' => 'Reading Frequency',
	'Class:PowerMeter/Attribute:powerreadingfrequency+' => 'Frequency for reading the meter',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:daily' => 'daily',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:daily+' => 'daily',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:monthly' => 'monthly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:monthly+' => 'monthly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:quarterly' => 'quarterly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:quarterly+' => 'quarterly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:weekly' => 'weekly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:weekly+' => 'weekly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:yearly' => 'yearly',
	'Class:PowerMeter/Attribute:powerreadingfrequency/Value:yearly+' => 'yearly',
	'Class:PowerMeter/Attribute:powerreadings_list' => 'Meter Readings',
	'Class:PowerMeter/Attribute:powerreadings_list+' => '',
	'Class:PowerMeter/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:PowerMeter/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: PowerMeterReadings
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:PowerMeterReadings' => 'Power Meter Reading',
	'Class:PowerMeterReadings+' => '',
	'Class:PowerMeterReadings/Attribute:readingdate' => 'Reading Date',
	'Class:PowerMeterReadings/Attribute:readingdate+' => '',
	'Class:PowerMeterReadings/Attribute:location_id' => 'Location',
	'Class:PowerMeterReadings/Attribute:location_id+' => '',
	'Class:PowerMeterReadings/Attribute:room_id' => 'Area',
	'Class:PowerMeterReadings/Attribute:room_id+' => '',
	'Class:PowerMeterReadings/Attribute:powermeter_id' => 'Power Meter',
	'Class:PowerMeterReadings/Attribute:powermeter_id+' => '',
	'Class:PowerMeterReadings/Attribute:organization' => 'Organization',
	'Class:PowerMeterReadings/Attribute:organization+' => 'Organization Meter belongs to',
	'Class:PowerMeterReadings/Attribute:powermeter_status' => 'Status',
	'Class:PowerMeterReadings/Attribute:powermeter_status+' => '',
	'Class:PowerMeterReadings/Attribute:reference' => 'Provider Reference',
	'Class:PowerMeterReadings/Attribute:reference+' => '',
	'Class:PowerMeterReadings/Attribute:frequency' => 'Reading Frequency',
	'Class:PowerMeterReadings/Attribute:frequency+' => '',
	'Class:PowerMeterReadings/Attribute:powermeter_voltage' => 'Rated Voltage (V)',
	'Class:PowerMeterReadings/Attribute:powermeter_voltage+' => '',
	'Class:PowerMeterReadings/Attribute:powermeter_current' => 'Rated Current (A)',
	'Class:PowerMeterReadings/Attribute:powermeter_current+' => '',
	'Class:PowerMeterReadings/Attribute:powermeter_phases' => 'Power Phases',
	'Class:PowerMeterReadings/Attribute:powermeter_phases+' => '',
	'Class:PowerMeterReadings/Attribute:previousreading' => 'Previous Reading Phase 1',
	'Class:PowerMeterReadings/Attribute:previousreading+' => '',
	'Class:PowerMeterReadings/Attribute:actualreading' => 'Actual Reading Phase 1',
	'Class:PowerMeterReadings/Attribute:actualreading+' => '',
	'Class:PowerMeterReadings/Attribute:previousreading2' => 'Previous Reading Phase 2',
	'Class:PowerMeterReadings/Attribute:previousreading2+' => '',
	'Class:PowerMeterReadings/Attribute:actualreading2' => 'Actual Reading Phase 2',
	'Class:PowerMeterReadings/Attribute:actualreading2+' => '',
	'Class:PowerMeterReadings/Attribute:previousreading3' => 'Previous Reading Phase 3',
	'Class:PowerMeterReadings/Attribute:previousreading3+' => '',
	'Class:PowerMeterReadings/Attribute:actualreading3' => 'Actual Reading Phase 3',
	'Class:PowerMeterReadings/Attribute:actualreading3+' => '',
	'Class:PowerMeterReadings/Attribute:billingdate' => 'Billing Date',
	'Class:PowerMeterReadings/Attribute:billingdate+' => '',
	'Class:PowerMeterReadings/Attribute:picture' => 'Picture Phase 1',
	'Class:PowerMeterReadings/Attribute:picture+' => 'Picture of actual reading Phase 1',
	'Class:PowerMeterReadings/Attribute:picture2' => 'Picture Phase 2',
	'Class:PowerMeterReadings/Attribute:picture2+' => 'Picture of actual reading Phase 2',
	'Class:PowerMeterReadings/Attribute:picture3' => 'Picture Phase 3',
	'Class:PowerMeterReadings/Attribute:picture3+' => 'Picture of actual reading Phase 3',
	'Class:PowerMeterReadings/Attribute:location_id_friendlyname' => 'location_id_friendlyname',
	'Class:PowerMeterReadings/Attribute:location_id_friendlyname+' => 'Full name',
	'Class:PowerMeterReadings/Attribute:location_id_obsolescence_flag' => 'Obsolete',
	'Class:PowerMeterReadings/Attribute:location_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:PowerMeterReadings/Attribute:room_id_friendlyname' => 'room_id_friendlyname',
	'Class:PowerMeterReadings/Attribute:room_id_friendlyname+' => 'Full name',
	'Class:PowerMeterReadings/Attribute:powermeter_id_friendlyname' => 'powermeter_id_friendlyname',
	'Class:PowerMeterReadings/Attribute:powermeter_id_friendlyname+' => 'Full name',
	'Class:PowerMeterReadings/Attribute:powermeter_id_obsolescence_flag' => 'Obsolete',
	'Class:PowerMeterReadings/Attribute:powermeter_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: genset
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:genset' => 'Power Generator',
	'Class:genset+' => '',
	'Class:genset/Attribute:ACDB_A_list' => 'AC-DBs Power A',
	'Class:genset/Attribute:ACDB_A_list+' => '',
	'Class:genset/Attribute:ACDB_B_list' => 'AC-DBs Power B',
	'Class:genset/Attribute:ACDB_B_list+' => '',
	'Class:genset/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:genset/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: dcpowerrectifier
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:dcpowerrectifier' => 'Power DC Rectifier',
	'Class:dcpowerrectifier+' => '',
	'Class:dcpowerrectifier/Attribute:powerstart_id' => 'Power Source',
	'Class:dcpowerrectifier/Attribute:powerstart_id+' => '',
	'Class:dcpowerrectifier/Attribute:powerstart_name' => 'Name',
	'Class:dcpowerrectifier/Attribute:powerstart_name+' => '',
	'Class:dcpowerrectifier/Attribute:dcdb_list' => 'DC-DBs',
	'Class:dcpowerrectifier/Attribute:dcdb_list+' => '',
	'Class:dcpowerrectifier/Attribute:device_powerA_list' => 'Devices Power A',
	'Class:dcpowerrectifier/Attribute:device_powerA_list+' => '',
	'Class:dcpowerrectifier/Attribute:device_powerB_list' => 'Devices Power B',
	'Class:dcpowerrectifier/Attribute:device_powerB_list+' => '',
	'Class:dcpowerrectifier/Attribute:ipaddress_id' => 'Management IP address',
	'Class:dcpowerrectifier/Attribute:ipaddress_id+' => '',
	'Class:dcpowerrectifier/Attribute:ipaddress_name' => 'FQDN',
	'Class:dcpowerrectifier/Attribute:ipaddress_name+' => 'Fully Qualified Domain Name',
	'Class:dcpowerrectifier/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:dcpowerrectifier/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:dcpowerrectifier/Attribute:powerstart_id_friendlyname' => 'Power Source Name',
	'Class:dcpowerrectifier/Attribute:powerstart_id_friendlyname+' => 'Full name',
	'Class:dcpowerrectifier/Attribute:powerstart_id_finalclass_recall' => 'Category',
	'Class:dcpowerrectifier/Attribute:powerstart_id_finalclass_recall+' => 'Category',
	'Class:dcpowerrectifier/Attribute:powerstart_id_obsolescence_flag' => 'Obsolete',
	'Class:dcpowerrectifier/Attribute:powerstart_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:dcpowerrectifier/Attribute:ipaddress_id_friendlyname' => 'Management IP address Name',
	'Class:dcpowerrectifier/Attribute:ipaddress_id_friendlyname+' => 'Full name',
	'Class:dcpowerrectifier/Attribute:ipaddress_id_finalclass_recall' => 'Class',
	'Class:dcpowerrectifier/Attribute:ipaddress_id_finalclass_recall+' => '',
));

//
// Class: acups
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:acups' => 'Power AC UPS',
	'Class:acups+' => '',
	'Class:acups/Attribute:powerstart_id' => 'Power Source',
	'Class:acups/Attribute:powerstart_id+' => '',
	'Class:acups/Attribute:powerstart_name' => 'Name',
	'Class:acups/Attribute:powerstart_name+' => '',
	'Class:acups/Attribute:PDU_list' => 'PDUs',
	'Class:acups/Attribute:PDU_list+' => '',
	'Class:acups/Attribute:device_powerA_list' => 'Devices Power A',
	'Class:acups/Attribute:device_powerA_list+' => '',
	'Class:acups/Attribute:device_powerB_list' => 'Devices Power B',
	'Class:acups/Attribute:device_powerB_list+' => '',
	'Class:acups/Attribute:ipaddress_id' => 'Management IP address',
	'Class:acups/Attribute:ipaddress_id+' => '',
	'Class:acups/Attribute:ipaddress_name' => 'FQDN',
	'Class:acups/Attribute:ipaddress_name+' => 'Fully Qualified Domain Name',
	'Class:acups/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:acups/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:acups/Attribute:powerstart_id_friendlyname' => 'Power Source Name',
	'Class:acups/Attribute:powerstart_id_friendlyname+' => 'Full name',
	'Class:acups/Attribute:powerstart_id_finalclass_recall' => 'Category',
	'Class:acups/Attribute:powerstart_id_finalclass_recall+' => 'Category',
	'Class:acups/Attribute:powerstart_id_obsolescence_flag' => 'Obsolete',
	'Class:acups/Attribute:powerstart_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:acups/Attribute:ipaddress_id_friendlyname' => 'IP address Name',
	'Class:acups/Attribute:ipaddress_id_friendlyname+' => 'Full name',
	'Class:acups/Attribute:ipaddress_id_finalclass_recall' => 'Class',
	'Class:acups/Attribute:ipaddress_id_finalclass_recall+' => '',
));

//
// Class: ACDB
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:ACDB' => 'Power AC DB',
	'Class:ACDB+' => '',
	'Class:ACDB/Attribute:powerstartA_id' => 'Power Source A',
	'Class:ACDB/Attribute:powerstartA_id+' => '',
	'Class:ACDB/Attribute:powerstartA_name' => 'Power Source A Name',
	'Class:ACDB/Attribute:powerstartA_name+' => '',
	'Class:ACDB/Attribute:powerstartB_id' => 'Power Source B',
	'Class:ACDB/Attribute:powerstartB_id+' => '',
	'Class:ACDB/Attribute:powerstartB_name' => 'Power Source B Name',
	'Class:ACDB/Attribute:powerstartB_name+' => '',
	'Class:ACDB/Attribute:redundancy' => 'Redundancy',
	'Class:ACDB/Attribute:redundancy+' => '',
	'Class:ACDB/Attribute:acups_list' => 'AC UPSs',
	'Class:ACDB/Attribute:acups_list+' => '',
	'Class:ACDB/Attribute:dcpowerrectifier_list' => 'DC Rectifiers',
	'Class:ACDB/Attribute:dcpowerrectifier_list+' => '',
	'Class:ACDB/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:ACDB/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:ACDB/Attribute:powerstartA_id_friendlyname' => 'Power Source A Name',
	'Class:ACDB/Attribute:powerstartA_id_friendlyname+' => 'Full name',
	'Class:ACDB/Attribute:powerstartA_id_finalclass_recall' => 'Category',
	'Class:ACDB/Attribute:powerstartA_id_finalclass_recall+' => 'Category',
	'Class:ACDB/Attribute:powerstartA_id_obsolescence_flag' => 'Obsolete',
	'Class:ACDB/Attribute:powerstartA_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:ACDB/Attribute:powerstartB_id_friendlyname' => 'Power Source B Name',
	'Class:ACDB/Attribute:powerstartB_id_friendlyname+' => 'Full name',
	'Class:ACDB/Attribute:powerstartB_id_finalclass_recall' => 'Category',
	'Class:ACDB/Attribute:powerstartB_id_finalclass_recall+' => 'Category',
	'Class:ACDB/Attribute:powerstartB_id_obsolescence_flag' => 'Obsolete',
	'Class:ACDB/Attribute:powerstartB_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: DCDB
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:DCDB' => 'Power DC DB',
	'Class:DCDB+' => 'DC Distribution Board',
	'Class:DCDB/Attribute:powerstart_id' => 'Power Source',
	'Class:DCDB/Attribute:powerstart_id+' => '',
	'Class:DCDB/Attribute:powerstart_name' => 'Power Source',
	'Class:DCDB/Attribute:powerstart_name+' => '',
	'Class:DCDB/Attribute:device_powerA_list' => 'Devices Power A',
	'Class:DCDB/Attribute:device_powerA_list+' => '',
	'Class:DCDB/Attribute:device_powerB_list' => 'Devices Power B',
	'Class:DCDB/Attribute:device_powerB_list+' => '',
	'Class:DCDB/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:DCDB/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:DCDB/Attribute:powerstart_id_friendlyname' => 'Power Source Name',
	'Class:DCDB/Attribute:powerstart_id_friendlyname+' => 'Full name',
	'Class:DCDB/Attribute:powerstart_id_finalclass_recall' => 'Category',
	'Class:DCDB/Attribute:powerstart_id_finalclass_recall+' => 'Category',
	'Class:DCDB/Attribute:powerstart_id_obsolescence_flag' => 'Obsolete',
	'Class:DCDB/Attribute:powerstart_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: SplicingTray
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:SplicingTray' => 'Fiber Splicing Tray',
	'Class:SplicingTray+' => '',
    'Class:SplicingTray/Attribute:name' => 'Name',
	'Class:SplicingTray/Attribute:name+' => '',
	'Class:SplicingTray/Attribute:fiberenclosure_id' => 'Fiber Enclosure',
	'Class:SplicingTray/Attribute:fiberenclosure_id+' => '',
	'Class:SplicingTray/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:SplicingTray/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
	'Class:SplicingTray/Attribute:fiberenclosure_id_friendlyname' => 'Fiber Enclosure Name',
	'Class:SplicingTray/Attribute:fiberenclosure_id_friendlyname+' => 'Full name',
	'Class:SplicingTray/Attribute:fiberenclosure_id_obsolescence_flag' => 'Obsolete',
	'Class:SplicingTray/Attribute:fiberenclosure_id_obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: FiberEnclosure
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:FiberEnclosure' => 'Fiber Enclosure',
	'Class:FiberEnclosure+' => '',
    'Class:FibreEnclosure/Attribute:name' => 'Name',
	'Class:FibreEnclosure/Attribute:name+' => '',
	'Class:FiberEnclosure/Attribute:splicingtray_list' => 'Splicing Trays',
	'Class:FiberEnclosure/Attribute:splicingtray_list+' => '',
	'Class:FiberEnclosure/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:FiberEnclosure/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
));

//
// Class: InlineEnclosure
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:InlineEnclosure' => 'Fiber Inline Enclosure',
	'Class:InlineEnclosure+' => '',
	'Class:InlineEnclosure/Attribute:splicingtray_list' => 'Splicing Trays',
	'Class:InlineEnclosure/Attribute:splicingtray_list+' => '',
	'Class:InlineEnclosure/Attribute:obsolescence_flag' => 'Obsolete',
	'Class:InlineEnclosure/Attribute:obsolescence_flag+' => 'Computed dynamically on other attributes',
));

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here
    'Class:Monitor/Attribute:name' => 'Name',
	'Class:Monitor/Attribute:name+' => '',
	'Class:DatacenterDevice/Attribute:voltage' => 'Operating Voltage (V)',
	'Class:DatacenterDevice/Attribute:voltage+' => '',
	'Class:DatacenterDevice/Attribute:voltage/Value:1' => '5',
	'Class:DatacenterDevice/Attribute:voltage/Value:1+' => '5',
	'Class:DatacenterDevice/Attribute:voltage/Value:2' => '12',
	'Class:DatacenterDevice/Attribute:voltage/Value:2+' => '12',
	'Class:DatacenterDevice/Attribute:voltage/Value:3' => '24',
	'Class:DatacenterDevice/Attribute:voltage/Value:3+' => '24',
	'Class:DatacenterDevice/Attribute:voltage/Value:4' => '48',
	'Class:DatacenterDevice/Attribute:voltage/Value:4+' => '48',
	'Class:DatacenterDevice/Attribute:voltage/Value:5' => '240',
	'Class:DatacenterDevice/Attribute:voltage/Value:5+' => '240',
	'Class:DatacenterDevice/Attribute:voltage/Value:6' => '400',
	'Class:DatacenterDevice/Attribute:voltage/Value:6+' => '400',
	'Class:DatacenterDevice/Attribute:current' => 'Nominal Current (A)',
	'Class:DatacenterDevice/Attribute:current+' => '',
	'Class:DatacenterDevice/Attribute:current/Value:1' => '6',
	'Class:DatacenterDevice/Attribute:current/Value:1+' => '6',
	'Class:DatacenterDevice/Attribute:current/Value:2' => '16',
	'Class:DatacenterDevice/Attribute:current/Value:2+' => '16',
	'Class:DatacenterDevice/Attribute:current/Value:3' => '20',
	'Class:DatacenterDevice/Attribute:current/Value:3+' => '20',
	'Class:DatacenterDevice/Attribute:current/Value:4' => '25',
	'Class:DatacenterDevice/Attribute:current/Value:4+' => '25',
	'Class:DatacenterDevice/Attribute:current/Value:5' => '40',
	'Class:DatacenterDevice/Attribute:current/Value:5+' => '40',
	'Class:DatacenterDevice/Attribute:current/Value:6' => '63',
	'Class:DatacenterDevice/Attribute:current/Value:6+' => '63',
	'Class:DatacenterDevice/Attribute:current/Value:7' => '80',
	'Class:DatacenterDevice/Attribute:current/Value:7+' => '80',
	'Class:DatacenterDevice/Attribute:current/Value:8' => '100',
	'Class:DatacenterDevice/Attribute:current/Value:8+' => '100',
	'Class:DatacenterDevice/Attribute:current/Value:9' => '125',
	'Class:DatacenterDevice/Attribute:current/Value:9+' => '125',
	'Class:DatacenterDevice/Attribute:phases' => 'Power Phases',
	'Class:DatacenterDevice/Attribute:phases+' => '',
	'Class:DatacenterDevice/Attribute:phases/Value:1-Phase' => '1-Phase',
	'Class:DatacenterDevice/Attribute:phases/Value:1-Phase+' => '1-Phase',
	'Class:DatacenterDevice/Attribute:phases/Value:3-Phase' => '3-Phase',
	'Class:DatacenterDevice/Attribute:phases/Value:3-Phase+' => '3-Phase',
));

//
// Class: Model
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:Model' => 'Model',
	'Class:Model+' => '',
	'Class:Model/Attribute:brand_id' => 'Brand',
	'Class:Model/Attribute:brand_id+' => '',
	'Class:Model/Attribute:brand_name' => 'Brand name',
	'Class:Model/Attribute:brand_name+' => '',
	'Class:Model/Attribute:type+' => '',
	'Class:Model/Attribute:type/Value:ACDB' => 'AC-DB',
	'Class:Model/Attribute:type/Value:ACDB+' => 'AC-DB',
	'Class:Model/Attribute:type/Value:Cabinet' => 'Cabinet',
	'Class:Model/Attribute:type/Value:Cabinet+' => 'Cabinet',
	'Class:Model/Attribute:type/Value:DCDB' => 'DC-DB',
	'Class:Model/Attribute:type/Value:DCDB+' => 'DC-DB',
	'Class:Model/Attribute:type/Value:FiberEnclosure' => 'Fiber Enclosure',
	'Class:Model/Attribute:type/Value:FiberEnclosure+' => 'Fiber Enclosure',
	'Class:Model/Attribute:type/Value:FloorPanel' => 'Floor Panel',
	'Class:Model/Attribute:type/Value:FloorPanel+' => 'Floor Panel',
	'Class:Model/Attribute:type/Value:InlineEnclosure' => 'Inline Enclosure',
	'Class:Model/Attribute:type/Value:InlineEnclosure+' => 'Inline Enclosure',
	'Class:Model/Attribute:type/Value:Monitor' => 'Monitor',
	'Class:Model/Attribute:type/Value:Monitor+' => 'Monitor',
	'Class:Model/Attribute:type/Value:NAS' => 'NAS',
	'Class:Model/Attribute:type/Value:NAS+' => 'NAS',
	'Class:Model/Attribute:type/Value:NetworkDevice' => 'Network Device',
	'Class:Model/Attribute:type/Value:NetworkDevice+' => 'Network Device',
	'Class:Model/Attribute:type/Value:PC' => 'PC',
	'Class:Model/Attribute:type/Value:PC+' => 'PC',
	'Class:Model/Attribute:type/Value:PDU' => 'PDU',
	'Class:Model/Attribute:type/Value:PDU+' => 'PDU',
	'Class:Model/Attribute:type/Value:PatchCable' => 'Patch Cable',
	'Class:Model/Attribute:type/Value:PatchCable+' => 'Patch Cable',
	'Class:Model/Attribute:type/Value:PatchPanel' => 'Patch Panel',
	'Class:Model/Attribute:type/Value:PatchPanel+' => 'Patch Panel',
	'Class:Model/Attribute:type/Value:Peripheral' => 'Peripheral',
	'Class:Model/Attribute:type/Value:Peripheral+' => 'Peripheral',
	'Class:Model/Attribute:type/Value:PowerMeter' => 'Power Meter',
	'Class:Model/Attribute:type/Value:PowerMeter+' => 'Power Meter',
	'Class:Model/Attribute:type/Value:Printer' => 'Printer',
	'Class:Model/Attribute:type/Value:Printer+' => 'Printer',
	'Class:Model/Attribute:type/Value:SANSwitch' => 'SAN Switch',
	'Class:Model/Attribute:type/Value:SANSwitch+' => 'SAN Switch',
	'Class:Model/Attribute:type/Value:Server' => 'Server',
	'Class:Model/Attribute:type/Value:Server+' => 'Server',
	'Class:Model/Attribute:type/Value:SplicingTray' => 'Splicing Tray',
	'Class:Model/Attribute:type/Value:SplicingTray+' => 'Splicing Tray',
	'Class:Model/Attribute:type/Value:StorageSystem' => 'Storage System',
	'Class:Model/Attribute:type/Value:StorageSystem+' => 'Storage System',
	'Class:Model/Attribute:type/Value:Tablet' => 'Tablet',
	'Class:Model/Attribute:type/Value:Tablet+' => 'Tablet',
	'Class:Model/Attribute:type/Value:TapeLibrary' => 'Tape Library',
	'Class:Model/Attribute:type/Value:TapeLibrary+' => 'Tape Library',
	'Class:Model/Attribute:type/Value:acups' => 'AC UPS',
	'Class:Model/Attribute:type/Value:acups+' => 'AC UPS',
	'Class:Model/Attribute:type/Value:dcpowerrectifier' => 'DC Rectifier',
	'Class:Model/Attribute:type/Value:dcpowerrectifier+' => 'DC Rectifier',
	'Class:Model/Attribute:type/Value:genset' => 'Power Generator',
	'Class:Model/Attribute:type/Value:genset+' => 'Power Generator',
	'Class:Model/Attribute:protection_class' => 'Protection Class',
	'Class:Model/Attribute:protection_class+' => '',
	'Class:Model/Attribute:protection_class/Value:1' => 'IP 51',
	'Class:Model/Attribute:protection_class/Value:2' => 'IP 52',
	'Class:Model/Attribute:protection_class/Value:3' => 'IP 53',
	'Class:Model/Attribute:protection_class/Value:4' => 'IP 54',
	'Class:Model/Attribute:protection_class/Value:5' => 'IP 55',
	'Class:Model/Attribute:protection_class/Value:6' => 'IP 56',
	'Class:Model/Attribute:protection_class/Value:7' => 'IP 57',
	'Class:Model/Attribute:protection_class/Value:8' => 'IP 61',
	'Class:Model/Attribute:protection_class/Value:9' => 'IP 62',
	'Class:Model/Attribute:protection_class/Value:10' => 'IP 63',
	'Class:Model/Attribute:protection_class/Value:11' => 'IP 64',
	'Class:Model/Attribute:protection_class/Value:12' => 'IP 65',
	'Class:Model/Attribute:protection_class/Value:13' => 'IP 66',
	'Class:Model/Attribute:protection_class/Value:14' => 'IP 67',
	'Class:Model/Attribute:protection_class/Value:15' => 'IP 68',
	'Class:Model/Attribute:physicaldevices_list' => 'Physical devices',
	'Class:Model/Attribute:physicaldevices_list+' => 'All the physical devices corresponding to this model',
	'Class:Model/Attribute:brand_id_friendlyname' => 'Brand',
	'Class:Model/Attribute:brand_id_friendlyname+' => 'Full name',
));

//
// Class: Incident
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:Incident' => 'Incident',
	'Class:Incident+' => '',
	'Class:Incident/Attribute:status' => 'Ticket Status',
	'Class:Incident/Attribute:status+' => '',
	'Class:Incident/Attribute:status/Value:new' => 'New',
	'Class:Incident/Attribute:status/Value:new+' => '',
	'Class:Incident/Attribute:status/Value:escalated_tto' => 'TTO breached',
	'Class:Incident/Attribute:status/Value:escalated_tto+' => 'Given time to assign the ticket was breached.',
	'Class:Incident/Attribute:status/Value:assigned' => 'Assigned',
	'Class:Incident/Attribute:status/Value:assigned+' => '',
	'Class:Incident/Attribute:status/Value:escalated_ttr' => 'TTR breached',
	'Class:Incident/Attribute:status/Value:escalated_ttr+' => 'Given time to resolve the ticket was breached.',
	'Class:Incident/Attribute:status/Value:waiting_for_approval' => 'Waiting for approval',
	'Class:Incident/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:Incident/Attribute:status/Value:pending' => 'Pending',
	'Class:Incident/Attribute:status/Value:pending+' => '',
	'Class:Incident/Attribute:status/Value:resolved' => 'Resolved',
	'Class:Incident/Attribute:status/Value:resolved+' => '',
	'Class:Incident/Attribute:status/Value:closed' => 'Closed',
	'Class:Incident/Attribute:status/Value:closed+' => '',
	'Class:Incident/Attribute:impact' => 'Impact',
	'Class:Incident/Attribute:impact+' => '',
	'Class:Incident/Attribute:impact/Value:1' => 'Entire Service',
	'Class:Incident/Attribute:impact/Value:1+' => 'e.g. all circuits or entire application',
	'Class:Incident/Attribute:impact/Value:2' => 'Multiple Service Locations',
	'Class:Incident/Attribute:impact/Value:2+' => 'e.g. several circuits or multiple users',
	'Class:Incident/Attribute:impact/Value:3' => 'Single Service Location',
	'Class:Incident/Attribute:impact/Value:3+' => 'e.g. one circuit or one user',
	'Class:Incident/Attribute:priority' => 'Priority',
	'Class:Incident/Attribute:priority+' => '',
	'Class:Incident/Attribute:priority/Value:1' => 'critical',
	'Class:Incident/Attribute:priority/Value:1+' => 'critical',
	'Class:Incident/Attribute:priority/Value:2' => 'high',
	'Class:Incident/Attribute:priority/Value:2+' => 'high',
	'Class:Incident/Attribute:priority/Value:3' => 'normal',
	'Class:Incident/Attribute:priority/Value:3+' => 'normal',
	'Class:Incident/Attribute:priority/Value:4' => 'low',
	'Class:Incident/Attribute:priority/Value:4+' => 'low',
	'Class:Incident/Attribute:urgency' => 'Urgency',
	'Class:Incident/Attribute:urgency+' => '',
	'Class:Incident/Attribute:urgency/Value:1' => 'critical',
	'Class:Incident/Attribute:urgency/Value:1+' => 'critical',
	'Class:Incident/Attribute:urgency/Value:2' => 'high',
	'Class:Incident/Attribute:urgency/Value:2+' => 'high',
	'Class:Incident/Attribute:urgency/Value:3' => 'normal',
	'Class:Incident/Attribute:urgency/Value:3+' => 'normal',
	'Class:Incident/Attribute:urgency/Value:4' => 'low',
	'Class:Incident/Attribute:urgency/Value:4+' => 'low',
	'Class:Incident/Attribute:origin' => 'Origin',
	'Class:Incident/Attribute:origin+' => '',
	'Class:Incident/Attribute:origin/Value:mail' => 'mail',
	'Class:Incident/Attribute:origin/Value:mail+' => 'mail',
	'Class:Incident/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:Incident/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:Incident/Attribute:origin/Value:phone' => 'phone',
	'Class:Incident/Attribute:origin/Value:phone+' => 'phone',
	'Class:Incident/Attribute:origin/Value:portal' => 'portal',
	'Class:Incident/Attribute:origin/Value:portal+' => 'portal',
	'Class:Incident/Attribute:service_id' => 'Service',
	'Class:Incident/Attribute:service_id+' => '',
	'Class:Incident/Attribute:service_name' => 'Service name',
	'Class:Incident/Attribute:service_name+' => '',
	'Class:Incident/Attribute:servicesubcategory_id' => 'Specific Service',
	'Class:Incident/Attribute:servicesubcategory_id+' => '',
	'Class:Incident/Attribute:servicesubcategory_name' => 'Specific Service name',
	'Class:Incident/Attribute:servicesubcategory_name+' => '',
	'Class:Incident/Attribute:escalation_flag' => 'Hot Flag',
	'Class:Incident/Attribute:escalation_flag+' => 'Flag to indicate highest priority',
	'Class:Incident/Attribute:escalation_flag/Value:no' => 'No',
	'Class:Incident/Attribute:escalation_flag/Value:no+' => 'No',
	'Class:Incident/Attribute:escalation_flag/Value:yes' => 'Yes',
	'Class:Incident/Attribute:escalation_flag/Value:yes+' => 'Yes',
	'Class:Incident/Attribute:escalation_reason' => 'Hot reason',
	'Class:Incident/Attribute:escalation_reason+' => '',
	'Class:Incident/Attribute:assignment_date' => 'Assignment date',
	'Class:Incident/Attribute:assignment_date+' => '',
	'Class:Incident/Attribute:resolution_date' => 'Resolution date',
	'Class:Incident/Attribute:resolution_date+' => '',
	'Class:Incident/Attribute:last_pending_date' => 'Last pending date',
	'Class:Incident/Attribute:last_pending_date+' => '',
	'Class:Incident/Attribute:cumulatedpending' => 'Cumulated pending',
	'Class:Incident/Attribute:cumulatedpending+' => '',
	'Class:Incident/Attribute:tto' => 'TTO',
	'Class:Incident/Attribute:tto+' => '',
	'Class:Incident/Attribute:ttr' => 'TTR',
	'Class:Incident/Attribute:ttr+' => '',
	'Class:Incident/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:Incident/Attribute:tto_escalation_deadline+' => '',
	'Class:Incident/Attribute:sla_tto_passed' => 'TTO breached',
	'Class:Incident/Attribute:sla_tto_passed+' => '',
	'Class:Incident/Attribute:sla_tto_over' => 'TTO breached by',
	'Class:Incident/Attribute:sla_tto_over+' => '',
	'Class:Incident/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:Incident/Attribute:ttr_escalation_deadline+' => '',
	'Class:Incident/Attribute:sla_ttr_passed' => 'TTR breached',
	'Class:Incident/Attribute:sla_ttr_passed+' => '',
	'Class:Incident/Attribute:sla_ttr_over' => 'TTR breached by',
	'Class:Incident/Attribute:sla_ttr_over+' => '',
	'Class:Incident/Attribute:time_spent' => 'Time to resolve',
	'Class:Incident/Attribute:time_spent+' => 'Time needed to resolve the incident',
	'Class:Incident/Attribute:resolution_code' => 'Resolution category',
	'Class:Incident/Attribute:resolution_code+' => '',
	'Class:Incident/Attribute:resolution_code/Value:assistance' => 'operating conditions normalized',
	'Class:Incident/Attribute:resolution_code/Value:assistance+' => 'if incident due to issues like power outage or system reboot',
	'Class:Incident/Attribute:resolution_code/Value:bug fixed' => 'cable repaired or replaced',
	'Class:Incident/Attribute:resolution_code/Value:bug fixed+' => 'if incident due to cabling issue',
	'Class:Incident/Attribute:resolution_code/Value:hardware repair' => 'hardware replacement or repair',
	'Class:Incident/Attribute:resolution_code/Value:hardware repair+' => 'if incident due to hardware issues',
	'Class:Incident/Attribute:resolution_code/Value:other' => 'configuration change',
	'Class:Incident/Attribute:resolution_code/Value:other+' => 'if incident due to configuration issues',
	'Class:Incident/Attribute:resolution_code/Value:software patch' => 'software patch applied',
	'Class:Incident/Attribute:resolution_code/Value:software patch+' => 'if incident due to software patch required',
	'Class:Incident/Attribute:resolution_code/Value:system update' => 'system update',
	'Class:Incident/Attribute:resolution_code/Value:system update+' => 'if incident due to system update required',
	'Class:Incident/Attribute:resolution_code/Value:training' => 'other, explained below',
	'Class:Incident/Attribute:resolution_code/Value:training+' => 'resolution to be described',
	'Class:Incident/Attribute:solution' => 'Solution',
	'Class:Incident/Attribute:solution+' => 'Short description of how the incident was resolved',
	'Class:Incident/Attribute:pending_reason' => 'Pending reason',
	'Class:Incident/Attribute:pending_reason+' => '',
	'Class:Incident/Attribute:parent_incident_id' => 'Parent incident',
	'Class:Incident/Attribute:parent_incident_id+' => '',
	'Class:Incident/Attribute:parent_incident_ref' => 'Parent incident ref',
	'Class:Incident/Attribute:parent_incident_ref+' => '',
	'Class:Incident/Attribute:parent_problem_id' => 'Parent problem',
	'Class:Incident/Attribute:parent_problem_id+' => '',
	'Class:Incident/Attribute:parent_problem_ref' => 'Parent problem ref',
	'Class:Incident/Attribute:parent_problem_ref+' => '',
	'Class:Incident/Attribute:parent_change_id' => 'Parent change',
	'Class:Incident/Attribute:parent_change_id+' => '',
	'Class:Incident/Attribute:parent_change_ref' => 'Parent change ref',
	'Class:Incident/Attribute:parent_change_ref+' => '',
	'Class:Incident/Attribute:related_request_list' => 'Child requests',
	'Class:Incident/Attribute:related_request_list+' => '',
	'Class:Incident/Attribute:child_incidents_list' => 'Child incidents',
	'Class:Incident/Attribute:child_incidents_list+' => 'All the child incidents related to this incident',
	'Class:Incident/Attribute:public_log' => 'Ticket Log',
	'Class:Incident/Attribute:public_log+' => '',
	'Class:Incident/Attribute:user_satisfaction' => 'User satisfaction',
	'Class:Incident/Attribute:user_satisfaction+' => '',
	'Class:Incident/Attribute:user_satisfaction/Value:1' => 'not shared',
	'Class:Incident/Attribute:user_satisfaction/Value:1+' => 'Customer did not share any opinion',
	'Class:Incident/Attribute:user_satisfaction/Value:2' => 'Satisfied',
	'Class:Incident/Attribute:user_satisfaction/Value:2+' => 'Satisfied',
	'Class:Incident/Attribute:user_satisfaction/Value:3' => 'Dissatisfied',
	'Class:Incident/Attribute:user_satisfaction/Value:3+' => 'Dissatisfied',
	'Class:Incident/Attribute:user_satisfaction/Value:4' => 'Very Dissatisfied',
	'Class:Incident/Attribute:user_satisfaction/Value:4+' => 'Very Dissatisfied',
	'Class:Incident/Attribute:user_comment' => 'User comment',
	'Class:Incident/Attribute:user_comment+' => '',
	'Class:Incident/Attribute:parent_incident_id_friendlyname' => 'parent_incident_id_friendlyname',
	'Class:Incident/Attribute:parent_incident_id_friendlyname+' => '',
	'Class:Incident/Stimulus:ev_assign' => 'Assign',
	'Class:Incident/Stimulus:ev_assign+' => '',
	'Class:Incident/Stimulus:ev_reassign' => 'Re-assign',
	'Class:Incident/Stimulus:ev_reassign+' => '',
	'Class:Incident/Stimulus:ev_pending' => 'Pending',
	'Class:Incident/Stimulus:ev_pending+' => '',
	'Class:Incident/Stimulus:ev_timeout' => 'Timeout',
	'Class:Incident/Stimulus:ev_timeout+' => '',
	'Class:Incident/Stimulus:ev_autoresolve' => 'Automatic resolve',
	'Class:Incident/Stimulus:ev_autoresolve+' => '',
	'Class:Incident/Stimulus:ev_autoclose' => 'Automatic close',
	'Class:Incident/Stimulus:ev_autoclose+' => '',
	'Class:Incident/Stimulus:ev_resolve' => 'Mark as resolved',
	'Class:Incident/Stimulus:ev_resolve+' => '',
	'Class:Incident/Stimulus:ev_close' => 'Close this request',
	'Class:Incident/Stimulus:ev_close+' => '',
	'Class:Incident/Stimulus:ev_reopen' => 'Re-open',
	'Class:Incident/Stimulus:ev_reopen+' => '',
	'Class:Incident/Error:CannotAssignParentIncidentIdToSelf' => 'Cannot assign the Parent incident to the incident itself',
	'Class:Incident/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:Incident/Method:ResolveChildTickets+' => 'Cascade the resolution to child ticket (ev_autoresolve), and align the following characteristics: service, team, agent, resolution info',
	'Tickets:Related:OpenIncidents' => 'Open incidents',
));

//
// Class: RequestTemplate
//
Dict::Add('EN US', 'English', 'English', array(
	'Class:RequestTemplate' => 'Request template',
	'Class:RequestTemplate+' => '',
	'Class:RequestTemplate/Attribute:service_id' => 'Service',
	'Class:RequestTemplate/Attribute:service_id+' => '',
	'Class:RequestTemplate/Attribute:service_name' => 'Service name',
	'Class:RequestTemplate/Attribute:service_name+' => '',
	'Class:RequestTemplate/Attribute:servicesubcategory_id' => 'Specific Service',
	'Class:RequestTemplate/Attribute:servicesubcategory_id+' => '',
	'Class:RequestTemplate/Attribute:servicesubcategory_name' => 'Specific Service name',
	'Class:RequestTemplate/Attribute:servicesubcategory_name+' => '',
	'Class:UserRequest/Attribute:service_details' => 'Service details',
	'Class:UserRequest/Attribute:service_details+' => 'Additionnal information depending on the service',
	'Class:Incident/Attribute:service_details' => 'Service details',
	'Class:Incident/Attribute:service_details+' => 'Additionnal information depending on the service',
	'Templates:UserData' => 'additional data',
	'Templates:Need' => 'required for:',
));

//
// Class: UserRequest
//

Dict::Add('EN US', 'English', 'English', array(
	'Class:UserRequest' => 'User Request',
	'Class:UserRequest+' => '',
	'Class:UserRequest/Attribute:status' => 'Ticket Status',
	'Class:UserRequest/Attribute:status+' => '',
	'Class:UserRequest/Attribute:status/Value:new' => 'New',
	'Class:UserRequest/Attribute:status/Value:new+' => '',
	'Class:UserRequest/Attribute:status/Value:escalated_tto' => 'TTO breached',
	'Class:UserRequest/Attribute:status/Value:escalated_tto+' => 'Given time to assign the ticket was breached.',
	'Class:UserRequest/Attribute:status/Value:assigned' => 'Assigned',
	'Class:UserRequest/Attribute:status/Value:assigned+' => '',
	'Class:UserRequest/Attribute:status/Value:escalated_ttr' => 'TTR breached',
	'Class:UserRequest/Attribute:status/Value:escalated_ttr+' => 'Given time to fulfill the request was breached.',
	'Class:UserRequest/Attribute:status/Value:waiting_for_approval' => 'Waiting for approval',
	'Class:UserRequest/Attribute:status/Value:waiting_for_approval+' => '',
	'Class:UserRequest/Attribute:status/Value:approved' => 'Approved',
	'Class:UserRequest/Attribute:status/Value:approved+' => '',
	'Class:UserRequest/Attribute:status/Value:rejected' => 'Rejected',
	'Class:UserRequest/Attribute:status/Value:rejected+' => '',
	'Class:UserRequest/Attribute:status/Value:pending' => 'Pending',
	'Class:UserRequest/Attribute:status/Value:pending+' => '',
	'Class:UserRequest/Attribute:status/Value:resolved' => 'Resolved',
	'Class:UserRequest/Attribute:status/Value:resolved+' => '',
	'Class:UserRequest/Attribute:status/Value:closed' => 'Closed',
	'Class:UserRequest/Attribute:status/Value:closed+' => '',
	'Class:UserRequest/Attribute:request_type' => 'Request Type',
	'Class:UserRequest/Attribute:request_type+' => '',
	'Class:UserRequest/Attribute:request_type/Value:service_request' => 'Service request',
	'Class:UserRequest/Attribute:request_type/Value:service_request+' => 'Service request',
	'Class:UserRequest/Attribute:impact' => 'Impact',
	'Class:UserRequest/Attribute:impact+' => '',
	'Class:UserRequest/Attribute:impact/Value:1' => 'Entire Services',
	'Class:UserRequest/Attribute:impact/Value:1+' => 'e.g. all circuits or entire application',
	'Class:UserRequest/Attribute:impact/Value:2' => 'Multiple Service Locations',
	'Class:UserRequest/Attribute:impact/Value:2+' => 'e.g. several circuits or multiple users',
	'Class:UserRequest/Attribute:impact/Value:3' => 'Single Service Location',
	'Class:UserRequest/Attribute:impact/Value:3+' => 'e.g. one circuit or one user',
	'Class:UserRequest/Attribute:priority' => 'Priority',
	'Class:UserRequest/Attribute:priority+' => '',
	'Class:UserRequest/Attribute:priority/Value:1' => 'critical',
	'Class:UserRequest/Attribute:priority/Value:1+' => 'critical',
	'Class:UserRequest/Attribute:priority/Value:2' => 'high',
	'Class:UserRequest/Attribute:priority/Value:2+' => 'high',
	'Class:UserRequest/Attribute:priority/Value:3' => 'normal',
	'Class:UserRequest/Attribute:priority/Value:3+' => 'normal',
	'Class:UserRequest/Attribute:priority/Value:4' => 'low',
	'Class:UserRequest/Attribute:priority/Value:4+' => 'low',
	'Class:UserRequest/Attribute:urgency' => 'Urgency',
	'Class:UserRequest/Attribute:urgency+' => '',
	'Class:UserRequest/Attribute:urgency/Value:1' => 'critical',
	'Class:UserRequest/Attribute:urgency/Value:1+' => 'critical',
	'Class:UserRequest/Attribute:urgency/Value:2' => 'high',
	'Class:UserRequest/Attribute:urgency/Value:2+' => 'high',
	'Class:UserRequest/Attribute:urgency/Value:3' => 'normal',
	'Class:UserRequest/Attribute:urgency/Value:3+' => 'normal',
	'Class:UserRequest/Attribute:urgency/Value:4' => 'low',
	'Class:UserRequest/Attribute:urgency/Value:4+' => 'low',
	'Class:UserRequest/Attribute:origin' => 'Origin',
	'Class:UserRequest/Attribute:origin+' => '',
	'Class:UserRequest/Attribute:origin/Value:mail' => 'mail',
	'Class:UserRequest/Attribute:origin/Value:mail+' => 'mail',
	'Class:UserRequest/Attribute:origin/Value:monitoring' => 'monitoring',
	'Class:UserRequest/Attribute:origin/Value:monitoring+' => 'monitoring',
	'Class:UserRequest/Attribute:origin/Value:phone' => 'phone',
	'Class:UserRequest/Attribute:origin/Value:phone+' => 'phone',
	'Class:UserRequest/Attribute:origin/Value:portal' => 'portal',
	'Class:UserRequest/Attribute:origin/Value:portal+' => 'portal',
	'Class:UserRequest/Attribute:approver_id' => 'Approver',
	'Class:UserRequest/Attribute:approver_id+' => '',
	'Class:UserRequest/Attribute:approver_email' => 'Approver Email',
	'Class:UserRequest/Attribute:approver_email+' => '',
	'Class:UserRequest/Attribute:service_id' => 'Service',
	'Class:UserRequest/Attribute:service_id+' => '',
	'Class:UserRequest/Attribute:service_name' => 'Service name',
	'Class:UserRequest/Attribute:service_name+' => '',
	'Class:UserRequest/Attribute:servicesubcategory_id' => 'Specific Service',
	'Class:UserRequest/Attribute:servicesubcategory_id+' => '',
	'Class:UserRequest/Attribute:servicesubcategory_name' => 'Specific Service name',
	'Class:UserRequest/Attribute:servicesubcategory_name+' => '',
	'Class:UserRequest/Attribute:escalation_flag' => 'Hot Flag',
	'Class:UserRequest/Attribute:escalation_flag+' => 'Flag to indicate highest priority',
	'Class:UserRequest/Attribute:escalation_flag/Value:no' => 'No',
	'Class:UserRequest/Attribute:escalation_flag/Value:no+' => 'No',
	'Class:UserRequest/Attribute:escalation_flag/Value:yes' => 'Yes',
	'Class:UserRequest/Attribute:escalation_flag/Value:yes+' => 'Yes',
	'Class:UserRequest/Attribute:escalation_reason' => 'Hot reason',
	'Class:UserRequest/Attribute:escalation_reason+' => '',
	'Class:UserRequest/Attribute:assignment_date' => 'Assignment date',
	'Class:UserRequest/Attribute:assignment_date+' => '',
	'Class:UserRequest/Attribute:resolution_date' => 'Resolution date',
	'Class:UserRequest/Attribute:resolution_date+' => '',
	'Class:UserRequest/Attribute:last_pending_date' => 'Last pending date',
	'Class:UserRequest/Attribute:last_pending_date+' => '',
	'Class:UserRequest/Attribute:cumulatedpending' => 'cumulatedpending',
	'Class:UserRequest/Attribute:cumulatedpending+' => '',
	'Class:UserRequest/Attribute:tto' => 'TTO',
	'Class:UserRequest/Attribute:tto+' => '',
	'Class:UserRequest/Attribute:ttr' => 'TTR',
	'Class:UserRequest/Attribute:ttr+' => '',
	'Class:UserRequest/Attribute:tto_escalation_deadline' => 'TTO Deadline',
	'Class:UserRequest/Attribute:tto_escalation_deadline+' => '',
	'Class:UserRequest/Attribute:sla_tto_passed' => 'TTO breached',
	'Class:UserRequest/Attribute:sla_tto_passed+' => '',
	'Class:UserRequest/Attribute:sla_tto_over' => 'TTO breached by',
	'Class:UserRequest/Attribute:sla_tto_over+' => '',
	'Class:UserRequest/Attribute:ttr_escalation_deadline' => 'TTR Deadline',
	'Class:UserRequest/Attribute:ttr_escalation_deadline+' => '',
	'Class:UserRequest/Attribute:sla_ttr_passed' => 'TTR breached',
	'Class:UserRequest/Attribute:sla_ttr_passed+' => '',
	'Class:UserRequest/Attribute:sla_ttr_over' => 'TTR breached by',
	'Class:UserRequest/Attribute:sla_ttr_over+' => '',
	'Class:UserRequest/Attribute:time_spent' => 'Time to resolve',
	'Class:UserRequest/Attribute:time_spent+' => 'Time needed to resolve the incident',
	'Class:UserRequest/Attribute:resolution_code' => 'Resolution category',
	'Class:UserRequest/Attribute:resolution_code+' => '',
	'Class:UserRequest/Attribute:resolution_code/Value:1' => 'request fulfilled as requested',
	'Class:UserRequest/Attribute:resolution_code/Value:1+' => 'request fulfilled as requested',
	'Class:UserRequest/Attribute:resolution_code/Value:2' => 'request fulfilled with alternative',
	'Class:UserRequest/Attribute:resolution_code/Value:2+' => 'request fulfilled with alternative',
	'Class:UserRequest/Attribute:resolution_code/Value:3' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:3+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:4' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:4+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:5' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:5+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:6' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:6+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:7' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:7+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:8' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:8+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:9' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:9+' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:10' => 'other',
	'Class:UserRequest/Attribute:resolution_code/Value:10+' => 'other',
	'Class:UserRequest/Attribute:solution' => 'Solution',
	'Class:UserRequest/Attribute:solution+' => 'Short description of how the request was fulfilled',
	'Class:UserRequest/Attribute:pending_reason' => 'Pending reason',
	'Class:UserRequest/Attribute:pending_reason+' => '',
	'Class:UserRequest/Attribute:parent_request_id' => 'Parent request',
	'Class:UserRequest/Attribute:parent_request_id+' => '',
	'Class:UserRequest/Attribute:parent_incident_id' => 'Parent incident',
	'Class:UserRequest/Attribute:parent_incident_id+' => '',
	'Class:UserRequest/Attribute:parent_request_ref' => 'Ref request',
	'Class:UserRequest/Attribute:parent_request_ref+' => '',
	'Class:UserRequest/Attribute:parent_problem_id' => 'Parent problem',
	'Class:UserRequest/Attribute:parent_problem_id+' => '',
	'Class:UserRequest/Attribute:parent_problem_ref' => 'Ref problem',
	'Class:UserRequest/Attribute:parent_problem_ref+' => '',
	'Class:UserRequest/Attribute:parent_change_id' => 'Parent change',
	'Class:UserRequest/Attribute:parent_change_id+' => '',
	'Class:UserRequest/Attribute:parent_change_ref' => 'Ref change',
	'Class:UserRequest/Attribute:parent_change_ref+' => '',
	'Class:UserRequest/Attribute:related_request_list' => 'Child Requests',
	'Class:UserRequest/Attribute:related_request_list+' => 'All the requests that are linked to this parent request',
	'Class:UserRequest/Attribute:public_log' => 'Public log',
	'Class:UserRequest/Attribute:public_log+' => '',
	'Class:UserRequest/Attribute:user_satisfaction' => 'User satisfaction',
	'Class:UserRequest/Attribute:user_satisfaction+' => '',
	'Class:UserRequest/Attribute:user_satisfaction/Value:1' => 'not shared',
	'Class:UserRequest/Attribute:user_satisfaction/Value:1+' => 'Customer did not share any opinion',
	'Class:UserRequest/Attribute:user_satisfaction/Value:2' => 'Satisfied',
	'Class:UserRequest/Attribute:user_satisfaction/Value:2+' => 'Satisfied',
	'Class:UserRequest/Attribute:user_satisfaction/Value:3' => 'Dissatisfied',
	'Class:UserRequest/Attribute:user_satisfaction/Value:3+' => 'Dissatisfied',
	'Class:UserRequest/Attribute:user_satisfaction/Value:4' => 'Very Dissatisfied',
	'Class:UserRequest/Attribute:user_satisfaction/Value:4+' => 'Very Dissatisfied',
	'Class:UserRequest/Attribute:user_comment' => 'User comment',
	'Class:UserRequest/Attribute:user_comment+' => '',
	'Class:UserRequest/Attribute:parent_request_id_friendlyname' => 'parent_request_id_friendlyname',
	'Class:UserRequest/Attribute:parent_request_id_friendlyname+' => '',
	'Class:UserRequest/Stimulus:ev_assign' => 'Assign',
	'Class:UserRequest/Stimulus:ev_assign+' => '',
	'Class:UserRequest/Stimulus:ev_reassign' => 'Re-assign',
	'Class:UserRequest/Stimulus:ev_reassign+' => '',
	'Class:UserRequest/Stimulus:ev_approve' => 'Approve',
	'Class:UserRequest/Stimulus:ev_approve+' => '',
	'Class:UserRequest/Stimulus:ev_reject' => 'Reject',
	'Class:UserRequest/Stimulus:ev_reject+' => '',
	'Class:UserRequest/Stimulus:ev_pending' => 'Pending',
	'Class:UserRequest/Stimulus:ev_pending+' => '',
	'Class:UserRequest/Stimulus:ev_timeout' => 'Timeout',
	'Class:UserRequest/Stimulus:ev_timeout+' => '',
	'Class:UserRequest/Stimulus:ev_autoresolve' => 'Automatic resolve',
	'Class:UserRequest/Stimulus:ev_autoresolve+' => '',
	'Class:UserRequest/Stimulus:ev_autoclose' => 'Automatic close',
	'Class:UserRequest/Stimulus:ev_autoclose+' => '',
	'Class:UserRequest/Stimulus:ev_resolve' => 'Mark as resolved',
	'Class:UserRequest/Stimulus:ev_resolve+' => '',
	'Class:UserRequest/Stimulus:ev_close' => 'Close this request',
	'Class:UserRequest/Stimulus:ev_close+' => '',
	'Class:UserRequest/Stimulus:ev_reopen' => 'Re-open',
	'Class:UserRequest/Stimulus:ev_reopen+' => '',
	'Class:UserRequest/Stimulus:ev_wait_for_approval' => 'Wait for approval',
	'Class:UserRequest/Stimulus:ev_wait_for_approval+' => '',
	'Class:UserRequest/Error:CannotAssignParentRequestIdToSelf' => 'Cannot assign the Parent request to the request itself',

	'Class:UserRequest/Method:ResolveChildTickets' => 'ResolveChildTickets',
	'Class:UserRequest/Method:ResolveChildTickets+' => 'Cascade the resolution to child requests (ev_autoresolve), and align the following characteristics of the request: service, team, agent, resolution info',
));

// Menu
//
Dict::Add('EN US', 'English', 'English', array(
	'Menu:DataSources' => 'Synchronization Data Sources',
	'Menu:DataSources+' => 'All Synchronization Data Sources',
	'Menu:WelcomeMenu' => 'My Dashboard',
	'Menu:WelcomeMenu+' => 'My Dashboard',
	'Menu:WelcomeMenuPage' => 'My Dashboard',
	'Menu:WelcomeMenuPage+' => 'My Dashboard',
	'Menu:AdminTools' => 'Admin tools',
	'Menu:AdminTools+' => 'Administration tools',
	'Menu:AdminTools?' => 'Tools accessible only to users having the administrator profile',
	'Menu:DataModelMenu' => 'Data Model',
	'Menu:DataModelMenu+' => 'Overview of the Data Model',
	'Menu:ExportMenu' => 'Export',
	'Menu:ExportMenu+' => 'Export the results of any query in HTML, CSV or XML',
	'Menu:NotificationsMenu' => 'Notifications',
	'Menu:NotificationsMenu+' => 'Configuration of the Notifications',
	'Menu:AuditCategories' => 'Audit Categories',
	'Menu:AuditCategories+' => 'Audit Categories',
	'Menu:Notifications:Title' => 'Audit Categories',
	'Menu:RunQueriesMenu' => 'Run Queries',
	'Menu:RunQueriesMenu+' => 'Run any query',
	'Menu:QueryMenu' => 'Query phrasebook',
	'Menu:QueryMenu+' => 'Query phrasebook',
	'Menu:UniversalSearchMenu' => 'Universal Search',
	'Menu:UniversalSearchMenu+' => 'Search for anything...',
	'Menu:UserManagementMenu' => 'User Management',
	'Menu:UserManagementMenu+' => 'User management',
	'Menu:ProfilesMenu' => 'Profiles',
	'Menu:ProfilesMenu+' => 'Profiles',
	'Menu:ProfilesMenu:Title' => 'Profiles',
	'Menu:UserAccountsMenu' => 'User Accounts',
	'Menu:UserAccountsMenu+' => 'User Accounts',
	'Menu:UserAccountsMenu:Title' => 'User Accounts',
	'Menu:MyShortcuts' => 'My Shortcuts',
));

Dict::Add('EN US', 'English', 'English', array(
	'Menu:IncidentManagement' => 'Incident Management',
	'Menu:IncidentManagement+' => 'Incident Management',
	'Menu:ChangeManagement' => 'Change Management',
	'Menu:ConfigManagement' => 'CMDB Management',
	'Menu:ConfigManagement+' => 'Configuration Management Database',
	'Menu:Incident:Overview' => 'Overview',
	'Menu:Incident:Overview+' => 'Overview',
	'Menu:NewIncident' => 'New incident',
	'Menu:NewIncident+' => 'Create a new incident ticket',
	'Menu:SearchIncidents' => 'Search for incidents',
	'Menu:SearchIncidents+' => 'Search for incident tickets',
	'Menu:Incident:Shortcuts' => 'Shortcuts',
	'Menu:Incident:Shortcuts+' => '',
	'Menu:Incident:MyIncidents' => 'Incidents assigned to me',
	'Menu:Incident:MyIncidents+' => 'Incidents assigned to me (as Agent)',
	'Menu:Incident:EscalatedIncidents' => 'Escalated incidents',
	'Menu:Incident:EscalatedIncidents+' => 'Escalated incidents',
	'Menu:Incident:OpenIncidents' => 'All open incidents',
	'Menu:Incident:OpenIncidents+' => 'All open incidents',
	'UI-IncidentManagementOverview-IncidentByPriority-last-14-days' => 'Last 14 days incident per priority',
	'UI-IncidentManagementOverview-Last-14-days' => 'Last 14 days number of incidents',
	'UI-IncidentManagementOverview-OpenIncidentByStatus' => 'Open incidents by status',
	'UI-IncidentManagementOverview-OpenIncidentByAgent' => 'Open incidents by agent',
	'UI-IncidentManagementOverview-OpenIncidentByCustomer' => 'Open incidents by customer',
));


?>
